# Site settings
author: Jonathan Koss
title: 
header-img: img/home-bg.png
email: jonathan_koss@yahoo.com
copyright_name: Jonathan Koss
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cantstopcoding

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
